### ISSUE TITLE
Import comment after sorting

### ISSUE THREAD

**Issue by kana-sama** [tweag/ormolu#870] opened 2022-04-06 15:31 UTC
**Describe the bug**
<img width="1337" alt="Screenshot 2022-04-06 at 19 28 40" src="https://user-images.githubusercontent.com/7101648/162011591-8d0956e3-3d00-4ece-9a57-c600355df0ca.png">

**To Reproduce**
```haskell
import {- A -} A
import {- Z -} Z
import {-# SOURCE #-} Y
import {- B -} B
```

**Expected behavior**
```haskell
import {- A -} A
import {- B -} B
import {-# SOURCE #-} Y
import {- Z -} Z
```

**Comment by amesgen** [comment] 2022-04-06 18:43
Thanks for the report, closing this as a duplicate of #469. If you need to preserve this exact layout, I would recommend to wrap this import block in [magic comments](https://github.com/tweag/ormolu#magic-comments=) for the time being:

```haskell
{- ORMOLU_DISABLE -}
import {- A -} A
import {- Z -} Z
import {-# SOURCE #-} Y
import {- B -} B
{- ORMOLU_ENABLE -}
```

**Closed by amesgen** 2022-04-06 18:43 UTC
