### ISSUE TITLE
Severe regression in 0.5.1.0

### ISSUE THREAD

**Issue by lehins** [tweag/ormolu#944] opened 2022-12-10 22:53 UTC
**Describe the bug**

Newer version of ormolu 0.5.1.0 has gotten much slower, especially when the `--no-cabal-flag` is not supplied.

**To Reproduce**

The exact timings can be reproduced on formatting the whole of https://github.com/lehins/massiv repository

```
> ghcup set ghc 9.4.3
...
> cabal install --overwrite-policy always ormolu-0.5.1.0
...
> ormolu --version
ormolu 0.5.1.0 UNKNOWN UNKNOWN
using ghc-lib-parser 9.4.3.20221104
> time ormolu -c -m inplace $(git ls-files -- '*.hs')
....
real	1m9.347s
user	1m9.340s
sys	0m0.048s
> time ormolu --no-cabal -c -m inplace $(git ls-files -- '*.hs')
...
real	0m18.807s
user	0m18.770s
sys	0m0.045s
```

Note that `--no-cabal-option` is much faster, but still not as fast as `0.5.0.1` version:

```
> ghcup set ghc 9.2.5
...
> cabal install --overwrite-policy always ormolu-0.5.0.1
...
> ormolu --version
ormolu 0.5.0.1 UNKNOWN UNKNOWN
using ghc-lib-parser 9.2.5.20221107
> time ormolu -c -m inplace $(git ls-files -- '*.hs')
...
real	0m5.710s
user	0m5.672s
sys	0m0.038s
> time ormolu --no-cabal -c -m inplace $(git ls-files -- '*.hs')
....
real	0m5.596s
user	0m5.574s
sys	0m0.022s
lehins@localhost:~/github/massiv> time ormolu -c -m inplace $(git ls-files -- '*.hs')
...
real	0m5.710s
user	0m5.672s
sys	0m0.038s
```

**Expected behavior**
Should not be that slow.

**Environment**
 - Linux x86_64

**Additional context**
None

**Comment by amesgen** [comment] 2022-12-10 23:03
Thanks for reporting, this seems to be a duplicate of #941, and it is unrelated to 0.5.1.0 vs 0.5.0.1, but rather a bug in GHC 9.4. Possible workarounds:

 - Disable the `fixity-th` flag when installing.
 - Compile 0.5.1.0 via e.g. 9.2.5 (the ghc-lib-parser version and the version Ormolu is compiled with are mostly independent).
 - Use the [prebuilt binaries](https://github.com/tweag/ormolu/releases/tag/0.5.1.0) (which are compiled via 9.2).

**Closed by amesgen** 2022-12-10 23:03 UTC

**Comment by amesgen** [comment] 2022-12-10 23:24
PR to disable `fixity-th` on GHC 9.4 for the time being: #945

**Comment by lehins** [comment] 2022-12-11 02:52
Is the fact that there is such a big discrepancy between presence/lack of `--no-cabal` flag also explained by `fixity-th`?

**Comment by amesgen** [comment] 2022-12-11 12:44
Yes; running a GHC 9.4 compiled Ormolu without `fixity-th` on e.g. the `massiv` codebase results in almost equal run times with and without `--no-cabal`.

For some context: The goal of the `fixity-th` flag is to remove a relatively small, constant time overhead every time the Ormolu binary is invoked. In particular, that means that enabling/disabling `fixity-th` makes only a small difference when formatting many files, but the relative difference is much bigger when formatting just a single, rather simple module (as is the case when e.g. invoking the Ormolu binary on every save in a text editor). For more details, see the benchmarks linked in the original PR #841.

On GHC 9.4, dumping a huge TH splice (which is what `fixity-th` does) seems to cause extremely weird performance behavior; we will have to look into that at some point (but as there are several easy workarounds, I haven't prioritized it so far).
