### ISSUE TITLE
Tuple sections formatted without spaces

### ISSUE THREAD

**Issue by oberblastmeister** [tweag/ormolu#1004] opened 2023-03-25 15:09 UTC
**Describe the bug**

Tuple sections are formatted like this:

```haskell
testing = (1,2,3,)
```

**Expected behavior**

I expect the formatted tuple sections to have spaces, especially when normal tuples are formatted like this:

```haskell
testing = (1, 2, 3)
```

**Environment**
 - OS name + version: Arch Linux
 - `ormolu 0.5.3.0 1b39d94d0c06aa53a577f7e0476695f9e6f5020b
using ghc-lib-parser 9.4.3.20221104`

**Comment by amesgen** [comment] 2023-03-25 15:10
Thanks, closing as a duplicate of #595.

**Closed by amesgen** 2023-03-25 15:10 UTC
