### ISSUE TITLE
Wrong formatting between the dollar sign and the next word

### ISSUE THREAD

**Issue by ryukzak** [tweag/ormolu#700] opened 2021-04-16 16:02 UTC
Wrong formatting between the dollar sign and the next word

**Describe the bug**
Wrong formatting between the dollar sign and the next word.

**To Reproduce**
```haskell
f = decideAt 1 1 $consume "a"
```
receive:
```haskell
f = decideAt 1 1 $consume "a"
--               ^
--               |
--               +--- no space here
```

**Expected behavior**

```haskell
f = decideAt 1  1 $ consume "a"
--                 ^
--                 |
--                 +--- add space here
```

**Environment**
 - OS name + version: https://monadfix.com/ormolu
 - Version of the code: ormolu commit a28f7b8, ormolu-live commit d8ae72e

**Comment by mheinzel** [comment] 2021-04-16 16:11
I'm not a maintainer, but this looks like a duplicate of https://github.com/tweag/ormolu/issues/699?

**Comment by ryukzak** [comment] 2021-04-16 17:03
You right.

**Closed** 2021-04-16 17:03 UTC
