### ISSUE TITLE
Group imports with same module name

### ISSUE THREAD

**Issue by guibou** [tweag/ormolu#552] opened 2020-04-16 13:39 UTC
**Is your feature request related to a problem? Please describe.**

The following multiples imports

```
import Foo (a, c)
import Foo (b)
```

in currently unchanged by ormolu.

**Describe the solution you'd like**

I'd like ormolu to group the imports when the context is the same (e.g. same module imported, same qualification and same alias) such as:

```
import Foo(a, b, c)
```

**Describe alternatives you've considered**

The current implementation can be left unchanged.

**Comment by basile-henry** [comment] 2020-04-17 10:19
I think it's a good idea! :smile:
 But doesn't this go against Ormolu trying to keep the AST of the module the same while formatting it? Or maybe this is not something Ormolu tries to achieve anymore?

**Comment by mrkkrp** [comment] 2020-04-17 11:04
Things like this are possible, but it is true that it's a bit more work because we need to take these transformations into account when we check that AST has not changed. We already do this because e.g. we sort import statements.

**Comment by mrkkrp** [comment] 2020-05-08 22:26
Duplicate of #414.

**Closed by mrkkrp** 2020-05-08 22:26 UTC
Labels: feature-request
