### ISSUE TITLE
Spaces before bang patterns in lambdas are lost, leading to unparseable \!

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#178] opened 2019-07-10 09:22 UTC
```haskell
f = \ !x -> x
```

Ormolu strips the space and promptly fails:

```
Parsing of formatted code failed:
<stdin><rendered>:1:5-6
parse error on input ‘\!’
Please, consider reporting the bug.
```

**Comment by int-index** [comment] 2019-07-11 18:20
A similar thing happens with lazy patterns:

```
mfix $ \ ~(rec_stackmaps, rec_high_sp, _new_blocks) ->
            layout dflags procpoints liveness entry entry_args
                   rec_stackmaps rec_high_sp blocks
```

is turned into

```
      mfix $ \~(rec_stackmaps, rec_high_sp, _new_blocks) ->
        layout dflags procpoints liveness entry entry_args
          rec_stackmaps
          rec_high_sp
          blocks
```

and fails with:

```
Parsing of formatted code failed:
<rendered>:258:14-15
parse error on input ‘\~’
Please, consider reporting the bug.
```

**Comment by mrkkrp** [comment] 2019-07-11 18:23
That should have been fixed by #153. Are you using the latest version of Ormolu?

**Comment by int-index** [comment] 2019-07-11 18:28
> Are you using the latest version of Ormolu?

As it turns out, I'm not. I updated to the latest version and now I get a different error on that file:

```
AST of input and AST of formatted code differ.
Please, consider reporting the bug.
```

The file is https://github.com/ghc/ghc/blob/6353efc7694ba8ec86c091918e02595662169ae2/compiler/cmm/CmmLayoutStack.hs

**Comment by mrkkrp** [comment] 2019-07-11 18:39
Try with `-u`.

**Comment by int-index** [comment] 2019-07-11 18:45
> Try with `-u`.

Sure, now it's reformatted, but my understanding of the error is that the GHC parser now produces a different AST from the re-formatted code, which is indicative of a bug? I'm not sure how to distill this into a useful bug report, there are other files which trigger the same error (see #200)

**Comment by yumiova** [comment] 2019-07-11 18:50
Would it be possible to make the diffing algorithm report lines that are potentially different, through e.g. `SrcSpan`s? That would make tracking down and reporting the cause of such errors much easier.

**Comment by mrkkrp** [comment] 2019-07-11 18:53
@int-index Sure, it's a bug. It's just with `-u` you can show us something more useful than

```
AST of input and AST of formatted code differ.
Please, consider reporting the bug.
```

That's why I asked to try with that option.

**Comment by int-index** [comment] 2019-07-11 18:56
>  It's just with -u you can show us something more useful than

And what would that be, now I just have a huge diff:

```
 compiler/cmm/CmmLayoutStack.hs | 1407 +++++++++--------
 1 file changed, 724 insertions(+), 683 deletions(-)
```

**Comment by mrkkrp** [comment] 2019-07-11 18:57
> Would it be possible to make the diffing algorithm report lines that are potentially different, through e.g. SrcSpans? That would make tracking down and reporting the cause of such errors much easier.

Potentially, but I wonder if it's worth the trouble. Usually it's more or less clear what is wrong. Making this detection work well will probably take more time than fixing most of the bugs that @neongreen reported. So we should choose carefully how we spend our resources to get a working solution sooner.

**Comment by mrkkrp** [comment] 2019-07-11 19:00
@int-index OK, let me try myself.

**Comment by mrkkrp** [comment] 2019-07-11 19:09
I was able to create a minimal repro from that file quite easily using binary search.

**Closed** 2019-07-13 15:45 UTC
Labels: bug, good first issue
