### ISSUE TITLE
CLI: Support specifying input folders in addition to just input files

### ISSUE THREAD

**Issue by matobet** [tweag/ormolu#910] opened 2022-07-15 01:03 UTC
It would be nice if fourmolu could take folders as well as files as an input and would process all haskell files in that folder (recursively)
so instead of
```
fourmolu -i $(find src -name '*.hs')
```
I'd be able to do just
```
fourmolu -i src
```
This is consistent what formatters in other languages support and would be a nice quality of life improvement.

**Comment by matobet** [comment] 2022-07-15 01:41
I dared to take a stab at this in https://github.com/tweag/ormolu/pull/911. Feedback welcome.

**Comment by matobet** [comment] 2022-07-16 22:06
For more advanced usages and patterns I definitely agree. But supporting the basic case as the "all *.hs files in this directory" seems to be a better UX overall and something a lot of users (including me) would expect to work out of the box. Just my $0.02.

**Comment by mrkkrp** [comment] 2023-01-05 15:09
Closing as a duplicate of #691.

**Closed by mrkkrp** 2023-01-05 15:09 UTC
Labels: feature-request
