### ISSUE TITLE
Only output is  "AST of input and AST of formatted code differ."

### ISSUE THREAD

**Issue by typetetris** [tweag/ormolu#686] opened 2021-02-23 16:55 UTC
We have a file, which results in the output
    
      AST of input and AST of formatted code differ.
      Please, consider reporting the bug.

So we have sadly no way to reduce it to a minimal example.

It would be very convenient if ormolu would just output the file created from the new ast, so we could have a look at it and identify, where the mismatch was.

**Comment by mrkkrp** [comment] 2021-02-23 17:02
What does `ormolu --version` say?

**Comment by typetetris** [comment] 2021-02-23 17:17
ormolu 0.1.4.1 UNKNOWN UNKNOWN
    using ghc-lib-parser 8.10.4.20210206

**Comment by mrkkrp** [comment] 2021-02-23 17:27
Normally, the positions in the original input (line/column number) are output as well. Apparently, in your case no such information is available. I can't help without a way to reproduce the issue.

**Comment by typetetris** [comment] 2021-02-23 17:28
Is there no way to get a representation of the new AST. We really don't want to disclose our source code.

**Comment by mrkkrp** [comment] 2021-02-23 20:26
Try to do binary search on the source code to figure out what triggers the error.

**Comment by mrkkrp** [comment] 2021-03-03 20:51
Closing due to lack of a reproducing example. If you manage to create one please re-open.

**Closed by mrkkrp** 2021-03-03 20:51 UTC
