### ISSUE TITLE
KindSignatures fail to parse

### ISSUE THREAD

**Issue by domenkozar** [tweag/ormolu#227] opened 2019-07-15 10:55 UTC
```haskell
{-# LANGUAGE KindSignatures #-}
module Foo where

addTag :: Proxy (s :: Symbol)
addTag = undefined
```

```
$ ./result/bin/ormolu --mode inplace Test.hs 
Parsing of formatted code failed:
Test.hs<rendered>:5:19-20
parse error on input ‘::’
Please, consider reporting the bug.
```

**Comment by neongreen** [comment] 2019-07-15 11:28
Duplicate of https://github.com/tweag/ormolu/issues/183

**Closed** 2019-07-15 12:58 UTC
