### ISSUE TITLE
doesn't install on ghc 9.2.1

### ISSUE THREAD

**Issue by GeorgeCo** [tweag/ormolu#831] opened 2021-11-05 12:31 UTC
doesn't install on ghc 9.2.1

```
bash-3.2$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
$ cabal install ormolu --allow-new
...
Building library for ormolu-0.3.1.0..
[ 1 of 47] Compiling GHC.DynFlags     ( src/GHC/DynFlags.hs, dist/build/GHC/DynFlags.o, dist/build/GHC/DynFlags.dyn_o )

src/GHC/DynFlags.hs:28:13: error:
    Not in scope: ‘platformMini’
    Perhaps you meant one of these:
      ‘platformMisc’ (imported from GHC.Driver.Session),
      data constructor ‘PlatformMisc’ (imported from GHC.Settings),
      ‘platformMinInt’ (imported from GHC.Platform)
   |
28 |             platformMini =
   |             ^^^^^^^^^^^^
...
bash-3.2$ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

**Comment by amesgen** [comment] 2021-11-05 12:52
Will be fixed by https://github.com/tweag/ormolu/pull/779 which should hopefully happen in the near future. Closing as a duplicate of https://github.com/tweag/ormolu/issues/794.

**Closed by amesgen** 2021-11-05 12:52 UTC

**Comment by GeorgeCo** [comment] 2021-11-05 14:58
Thanks for the very quick response, good news 👍
