### ISSUE TITLE
Would it be possible to normalise superfluous parentheses?

### ISSUE THREAD

**Issue by aspiwack** [tweag/ormolu#584] opened 2020-05-12 09:02 UTC
**Is your feature request related to a problem? Please describe.**

I noticed that a function such as:
```haskell
f :: (Monad m) => a -> m a
f = return
```

is formatted as itself.

The parentheses around `Monad m` is entirely superfluous, and a number of style guides frown on such extraneous parenthesis.

**Describe the solution you'd like**

Would it be possible to remove such parenthesis? I'm not sure that it's reasonable to hunt for parentheses everywhere and remove them at all cost. But Ormolu could remove them in constraint lists at least, that would be useful. We can look for more opportunities later if this proves to be a good idea.

**Comment by mrkkrp** [comment] 2020-05-12 13:36
Duplicate of #264.

**Closed by mrkkrp** 2020-05-12 13:36 UTC
