### ISSUE TITLE
Idempotence bug with consecutive haddocks

### ISSUE THREAD

**Issue by santiweight** [tweag/ormolu#889] opened 2022-05-27 02:13 UTC
The following throws an idempotence issue on version:
```
ormolu 0.4.0.0 UNKNOWN UNKNOWN
using ghc-lib-parser 9.2.2.20220307
```

Starting with:

```
  -- | Foo
  -- | Foo
data Foo = Foo
```

gives:

```
-- Foo
-- | Foo
data Foo = Foo
```

gives:

```
-- Foo

-- | Foo
data Foo = Foo
```

Looks like an idempotence bug to me :)

**Comment by amesgen** [comment] 2022-05-27 09:18
Thanks, this is a duplicate of https://github.com/tweag/ormolu/issues/816#issuecomment-968935885, which was fixed in https://github.com/tweag/ormolu/pull/837 and is part of 0.5.0.0, while you are using 0.4.0.0.

**Closed by amesgen** 2022-05-27 09:18 UTC
