### ISSUE TITLE
Feature Request: Break import sorting with Stanzas

### ISSUE THREAD

**Issue by CaptJakk** [tweag/ormolu#481] opened 2019-12-14 22:36 UTC
I didn't see this mentioned before. But one of the things I do often and have seen others do as well is have separate import stanzas for prelude, external modules, and internal modules. This helps at a glance to know where things came from.

Example:
Today it formats from this:

```haskell
import MyPrelude

import Data.Text
import Data.ByteString
```

to this:
```
import Data.ByteString
import Data.Text
import MyPrelude
```

After the proposed change it would instead be reformatted to this:
```haskell
import MyPrelude

import Data.ByteString
import Data.Text
```

What do you guys think?

**Comment by mrkkrp** [comment] 2019-12-15 14:15
Duplicate of #74, see discussion there for why multiple blocks is considered not a good idea.

**Closed by mrkkrp** 2019-12-15 14:15 UTC

**Comment by turion** [comment] 2022-03-11 12:06
`cargo fmt` does this as well for Rust. I personally think it would be a great idea.
