### ISSUE TITLE
Combination of non-docstring and docstring comment gets AST-clobbered

### ISSUE THREAD

**Issue by infinity0** [tweag/ormolu#614] opened 2020-06-14 19:06 UTC
```haskell
import Prelude -- separate issue, but without this line haddock fails

{- | Main docstring -}
-- non-docstring comment
main :: IO ()
main = pure ()
```

~~~~
$ haddock --version
Haddock version 2.24.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
$ haddock Test.hs -h
Haddock coverage:
Warning: Package name is not available.
  50% (  1 /  2) in 'Main'
  Missing documentation for:
    Module header
Warning: Main: could not find link destinations for:
    IO
$ ormolu -d -minplace Test.hs
warnings:


parse result:
  comment stream:
Test.hs:1:16-69 Comment True ("-- separate issue, but without this line haddock fails" :| [])
Test.hs:4:1-24 Comment False ("-- non-docstring comment" :| [])


AST of input and AST of formatted code differ.
  at Test.hs:3:1-22
Please, consider reporting the bug.

5
~~~~

**Comment by mrkkrp** [comment] 2020-06-15 08:42
Duplicate of #589.

**Closed by mrkkrp** 2020-06-15 08:42 UTC
